package de.amr.games.pacman.event;

/**
 * @author Armin Reichert
 */
public enum GameEventType {
    BONUS_ACTIVATED,
    BONUS_EATEN,
    BONUS_EXPIRED,
    CREDIT_ADDED,
    CUSTOM_MAPS_CHANGED,
    EXTRA_LIFE_WON,
    GAME_STATE_CHANGED,
    GAME_VARIANT_CHANGED,
    GHOST_EATEN,
    GHOST_ENTERS_HOUSE,
    GHOST_STARTS_RETURNING_HOME,
    HUNTING_PHASE_STARTED,
    INTERMISSION_STARTED,
    LEVEL_CREATED,
    LEVEL_STARTED,
    PAC_DYING,
    PAC_FOUND_FOOD,
    PAC_GETS_POWER,
    PAC_LOST_POWER,
    PAC_STARTS_LOSING_POWER,
    STOP_ALL_SOUNDS,

    UNSPECIFIED_CHANGE;
}