[versions]
tinylog = "2.7.0"

[libraries]
tinylog-api = { module = "org.tinylog:tinylog-api", version.ref = "tinylog"}
tinylog-impl = { module = "org.tinylog:tinylog-impl", version.ref = "tinylog"}

[bundles]
tinylog = ["tinylog-api", "tinylog-impl"]