name: Build All Modules

on:
  push:
    branches: [ "**" ]
  pull_request:

env:
  _JAVA_OPTIONS: "-Djava.net.preferIPv4Stack=true"

jobs:
  build:
    strategy:
      matrix:
        #os: [windows-latest, ubuntu-latest, macos-14]
        os: [windows-latest]
        java: ['25']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}

    steps:
      - name: Checkout pacman-javafx
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v4

      - name: Build project
        run: ./gradlew build --no-daemon
